# Generated by Django 4.0.5 on 2022-06-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='IsOrganizationalAccount',
            field=models.BooleanField(default=False, verbose_name='حساب سازمانی میباشد'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='User_national_code',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='کد ملی '),
        ),
    ]
