# Generated by Django 4.0.5 on 2022-06-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_myuser_isorganizationalaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='User_national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی '),
        ),
    ]
