# Generated by Django 4.0.5 on 2022-06-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='User_mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل1'),
        ),
    ]
