# Generated by Django 4.0.5 on 2022-06-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_myuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('City_name', models.CharField(max_length=30, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'CityName',
                'verbose_name_plural': 'CityNames',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('Unit_name', models.CharField(max_length=30, verbose_name='نام واحد')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.city')),
            ],
            options={
                'verbose_name': 'UnitName',
                'verbose_name_plural': 'UnitNames',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('Admin_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.city')),
                ('Admin_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.unit')),
                ('Admin_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
